name = "Silicon Valley Adventure"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0777dc1b4d6088876e6e256d511770cbdeb0fd40fe2505619ecc1ecfafadc972"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
