name = "Silicon Valley Adventure"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6ffa7c58071bb5f670370fa0ebbcad4af044711c4ffcc31f4dc6fb109c28ccc"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
