name = "Silicon Valley Adventure"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d966ce5a58166efe4564f6d2093d4f9ac0eae3f1927f44ad2469950110af6ce"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
