name = "Silicon Valley Adventure"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d05f9052d18f1a5cba6974b5a3d8f801081c8a0a0a0f3d34ad1cab26273df597"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
