name = "Silicon Valley Adventure"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03157255b7d722d9b2a01ae59a2542d1a71f56b6593edb5cfb5a4969088319b8"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
