name = "Silicon Valley Adventure"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dd305fa04fa6eaba1df25142ef0e11e36936bf6ff3dbc890407b63534b51613"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
